APP_TITLE = "RF Explorer Linux Viewer"
DEFAULT_BAUD = 500000
DEFAULT_TOP_DBM = 0
DEFAULT_BOTTOM_DBM = -120
DEFAULT_PEAK_TIMEOUT_SEC = 2.5
DEFAULT_HISTORY_DEPTH = 45
DEFAULT_HISTORY_REDRAW_SEC = 0.22
MAX_PEAKS = 5
MAX_HISTORY_DEPTH = 180
PEAK_MATCH_WINDOW_MHZ = 0.35
FREQUENCY_AXIS_TOLERANCE_MHZ = 0.05

